version: "3"
services:

  locust-master:
    image: swernst/locusts
    volumes:
      - ./scripts:/scripts
    networks:
      - backend
    ports:
      - "8089:8089"

  locust-worker:
    image: swernst/locusts
    command: "--master-host=locust-master"
    volumes:
      - ./scripts:/scripts
    networks:
      - backend

  # influxdb:
  #   image: influxdb:alpine
  #   networks:
  #     - backend
  #   ports:
  #     - "8086:8086" #HTTP API
  #   environment:
  #     - INFLUXDB_DB=gatling
  #   volumes:
  #     - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro

networks:
  backend:
